stages:
- build
- deploy

# Stage I
# Build Phase:
# This is where the main code is built.
build:
  image: docker:dind
  stage: build
  script:
    - sudo docker ps
    - sudo docker-compose down
    - sudo docker-compose build



# Stage III
# Deploying Phase:
# This is where the main code is deployed to our server at AWS.
deploy:
  only:
    - master
  stage: deploy
  image: node:alpine
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  script:
    - bash deploy/deploy.sh
