stages:
- build
- deploy

# Stage I
# Build Phase:
# This is where the main code is built.
build:
  image: docker:dind
  stage: build
  script:
    - sudo docker ps
    - sudo docker-compose down
    - sudo docker-compose build



# Stage III
# Deploying Phase:
# This is where the main code is deployed to our server at AWS.
deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - mkdir sshkey
    - echo "$SSH_KEY_APP" >> ./sshkey/git-breakdown.pem
    - chmod 600 ./sshkey/git-breakdown.pem

  script:
    - ssh ubuntu@54.164.24.112 -i git-breakdown.pem
    - sudo docker-compose down
    - rm -rf 2019.2-Git-Breakdown
    - git clone https://github.com/fga-eps-mds/2019.2-Git-Breakdown.git
    - cd 2019.2-Git-Breakdown
    - sudo docker-compose build --no-cache
    - sudo docker-compose up -d
    - exit

  only:
    - master